const IMG = s => `https://commons.wikimedia.org/wiki/Special:FilePath/${s}`

export const plants = [
  // ── TAJIKISTAN ──────────────────────────────────────────────
  { id:1, name:'Nurek HPP', nameRu:'Нурекская ГЭС', type:'hydro',
    lng:69.34806, lat:38.37167, capacity:3015, country:'Tajikistan', countryRu:'Таджикистан',
    river:'Vakhsh', riverRu:'Вахш', status:'active', year:1972, annual:'11 TWh', units:9,
    img: IMG('Nurek_Dam.JPG'),
    description:'Second-tallest dam in the world at 304 m. Nine 335 MW Francis turbines producing ~11 TWh/year, supplying over 70% of Tajikistan\'s electricity.',
    descriptionRu:'Вторая по высоте плотина в мире — 304 м. Девять турбин по 335 МВт вырабатывают ~11 ТВт·ч/год и обеспечивают более 70% электроэнергии Таджикистана.' },
  { id:2, name:'Rogun HPP', nameRu:'Рогунская ГЭС', type:'hydro',
    lng:69.77194, lat:38.68306, capacity:3600, country:'Tajikistan', countryRu:'Таджикистан',
    river:'Vakhsh', riverRu:'Вахш', status:'construction', year:2018, annual:'13.3 TWh', units:6,
    img: IMG('Rogun_Dam.jpg'),
    description:'When complete, will be the world\'s tallest dam at 335 m. Six 600 MW turbines planned. Two units already operational since 2018–2019.',
    descriptionRu:'После завершения — самая высокая плотина в мире (335 м). Шесть турбин по 600 МВт. Два агрегата уже работают с 2018–2019 гг.' },
  { id:3, name:'Sangtuda-1 HPP', nameRu:'Сангтудинская ГЭС-1', type:'hydro',
    lng:69.05833, lat:38.04500, capacity:670, country:'Tajikistan', countryRu:'Таджикистан',
    river:'Vakhsh', riverRu:'Вахш', status:'active', year:2009, annual:'2.7 TWh', units:4,
    img: IMG('Sangtuda_1.jpg'),
    description:'Four 167.5 MW run-of-river turbines. Built with Russian investment; generates ~12% of Tajikistan\'s national electricity output.',
    descriptionRu:'Четыре турбины по 167,5 МВт. Построена с российскими инвестициями; даёт ~12% национальной выработки электроэнергии.' },
  { id:4, name:'Pamir-1 HPP', nameRu:'Памир-1 ГЭС', type:'hydro',
    lng:71.47000, lat:37.49000, capacity:28, country:'Tajikistan', countryRu:'Таджикистан',
    river:'Gunt', riverRu:'Гунт', status:'active', year:2006, annual:'0.15 TWh', units:2,
    img: null,
    description:'Main power source for the entire Gorno-Badakhshan region (GBAO), including Khorog city. Operated by Pamir Energy (Aga Khan Fund).',
    descriptionRu:'Основной источник электроэнергии для всего Горно-Бадахшанского региона, включая город Хорог. Управляется Pamir Energy (Фонд Ага-Хана).' },
  { id:5, name:'Kairakkum HPP', nameRu:'Кайраккумская ГЭС', type:'hydro',
    lng:69.81612, lat:40.27702, capacity:174, country:'Tajikistan', countryRu:'Таджикистан',
    river:'Syrdarya', riverRu:'Сырдарья', status:'active', year:1956, annual:'0.9 TWh', units:6,
    img: null,
    description:'Oldest major HPP in Tajikistan, located in the northern Sughd Region. Modernised from 126 MW to 174 MW. Also regulates irrigation.',
    descriptionRu:'Старейшая крупная ГЭС Таджикистана, расположена в Согдийской области. Модернизирована с 126 до 174 МВт. Регулирует орошение.' },
  { id:6, name:'Dushanbe-2 CHP', nameRu:'Душанбинская ТЭЦ-2', type:'coal',
    lng:68.77256, lat:38.60983, capacity:400, country:'Tajikistan', countryRu:'Таджикистан',
    river:null, status:'active', year:2016, annual:'2 TWh', units:3,
    img: null,
    description:'Coal-fired CHP plant built by Chinese contractor, financed by China Exim Bank. Critical winter backup for Dushanbe when hydro output drops.',
    descriptionRu:'Угольная ТЭЦ, построенная китайским подрядчиком на средства China Exim Bank. Критически важный зимний резерв для Душанбе.' },
  { id:7, name:'Baipaza HPP', nameRu:'Байпазинская ГЭС', type:'hydro',
    lng:69.12341, lat:38.26780, capacity:600, country:'Tajikistan', countryRu:'Таджикистан',
    river:'Vakhsh', riverRu:'Вахш', status:'active', year:1985, annual:'2.2 TWh', units:4,
    img: null,
    description:'Part of the Vakhsh river cascade. Four 150 MW Francis turbines feeding the southern Tajik grid.',
    descriptionRu:'Часть каскада ГЭС на реке Вахш. Четыре турбины по 150 МВт питают энергосистему юга Таджикистана.' },
  { id:8, name:'Sangtuda-2 HPP', nameRu:'Сангтудинская ГЭС-2', type:'hydro',
    lng:69.02694, lat:37.97083, capacity:220, country:'Tajikistan', countryRu:'Таджикистан',
    river:'Vakhsh', riverRu:'Вахш', status:'active', year:2011, annual:'1 TWh', units:2,
    img: IMG('SGII-Dam.JPG'),
    description:'Built with Iranian investment, two 110 MW turbines downstream of Sangtuda-1.',
    descriptionRu:'Построена с иранскими инвестициями, две турбины по 110 МВт ниже по течению от Сангтуда-1.' },
  { id:9, name:'Golovnaya HPP', nameRu:'Головная ГЭС', type:'hydro',
    lng:68.93727, lat:37.88514, capacity:240, country:'Tajikistan', countryRu:'Таджикистан',
    river:'Vakhsh', riverRu:'Вахш', status:'active', year:1962, annual:'1.4 TWh', units:4,
    img: null,
    description:'Oldest station in the Vakhsh cascade, regulates flow for the downstream irrigation canals.',
    descriptionRu:'Старейшая станция каскада на реке Вахш, регулирует сток для ирригационных каналов ниже по течению.' },

  // ── CHINA ───────────────────────────────────────────────────
  { id:10, name:'Three Gorges Dam', nameRu:'ГЭС «Три ущелья»', type:'hydro',
    lng:110.985, lat:30.823, capacity:22500, country:'China', countryRu:'Китай',
    river:'Yangtze', riverRu:'Янцзы', status:'active', year:2003, annual:'88.2 TWh', units:34,
    img: IMG('Three_Gorges_Dam%2C_Yangtze_River%2C_China.jpg'),
    description:'World\'s largest power station by installed capacity. 34 turbines of 700–778 MW each. The reservoir stretches 600 km upstream and displaced 1.3 million people.',
    descriptionRu:'Крупнейшая электростанция мира по установленной мощности. 34 турбины по 700–778 МВт. Водохранилище длиной 600 км затопило территорию с 1,3 млн жителей.' },
  { id:11, name:'Tianwan Nuclear', nameRu:'АЭС Тяньвань', type:'nuclear',
    lng:119.460, lat:34.690, capacity:6900, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2007, annual:'50 TWh', units:8,
    img: null,
    description:'Largest nuclear power plant in China, built in cooperation with Russia (Rosatom). Eight VVER-1000 reactors; four more units under construction.',
    descriptionRu:'Крупнейшая АЭС Китая, построена в сотрудничестве с Россией (Росатом). Восемь реакторов ВВЭР-1000; ещё четыре блока строятся.' },
  { id:12, name:'Tuoketuo Power Station', nameRu:'Электростанция Туокэтуо', type:'coal',
    lng:111.060, lat:40.290, capacity:6720, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2006, annual:'39 TWh', units:12,
    img: null,
    description:'World\'s largest coal-fired power plant by installed capacity. Located in Inner Mongolia, supplying electricity to Beijing and surrounding regions.',
    descriptionRu:'Крупнейшая угольная электростанция мира по установленной мощности. Расположена во Внутренней Монголии, снабжает электроэнергией Пекин и прилегающие регионы.' },
  { id:13, name:'Huanghe Hydropower Solar Park', nameRu:'Солнечный парк Хуанхэ', type:'solar',
    lng:98.050, lat:36.070, capacity:2200, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2020, annual:'3.9 TWh', units:null,
    img: null,
    description:'One of the world\'s largest solar farms, located on the Qinghai Plateau at 3,000 m elevation. Combines solar panels with sheep grazing below.',
    descriptionRu:'Один из крупнейших солнечных парков мира на Цинхайском плато, высота 3000 м. Сочетает солнечные панели с выпасом овец.' },
  { id:14, name:'Gansu Wind Farm', nameRu:'Ветропарк Ганьсу', type:'wind',
    lng:97.000, lat:39.500, capacity:8000, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2010, annual:'17 TWh', units:5000,
    img: null,
    description:'World\'s largest wind farm complex by capacity. Located in the Gobi Desert corridor. Part of China\'s plan to reach 1,200 GW of wind capacity by 2030.',
    descriptionRu:'Крупнейший в мире ветроэнергетический комплекс по мощности. Расположен в коридоре пустыни Гоби. Часть китайского плана по ветровой энергетике.' },
  { id:15, name:'Xiluodu Dam', nameRu:'ГЭС Силоду', type:'hydro',
    lng:103.640, lat:28.255, capacity:13860, country:'China', countryRu:'Китай',
    river:'Jinsha', riverRu:'Цзиньшацзян', status:'active', year:2014, annual:'57 TWh', units:18,
    img: null,
    description:'Fourth-largest power station in the world. One of the tallest dams in China on the upper Yangtze tributary Jinsha River.',
    descriptionRu:'Четвёртая по мощности электростанция мира. Одна из самых высоких плотин Китая на притоке Янцзы — реке Цзиньшацзян.' },
  { id:16, name:'Wudongde Dam', nameRu:'ГЭС Удундэ', type:'hydro',
    lng:102.635, lat:26.339, capacity:10200, country:'China', countryRu:'Китай',
    river:'Jinsha', riverRu:'Цзиньшацзян', status:'active', year:2021, annual:'38.9 TWh', units:12,
    img: null,
    description:'Part of the Jinsha River hydropower cascade, with the world\'s highest 300 m-class double-curvature arch dam.',
    descriptionRu:'Часть каскада ГЭС на реке Цзиньшацзян. Самая высокая в мире двухкривизненная арочная плотина класса 300 м.' },
  { id:17, name:'Tengger Desert Solar Park', nameRu:'Солнечный парк Тэнгер', type:'solar',
    lng:104.950, lat:37.500, capacity:1547, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2016, annual:'2.5 TWh', units:null,
    img: null,
    description:'Once the world\'s largest single PV plant, nicknamed the "Great Wall of Solar". Spans the Tengger Desert in Ningxia.',
    descriptionRu:'Некогда крупнейшая фотовольтаическая станция мира, прозванная «Великой солнечной стеной». Расположена в пустыне Тэнгер, Нинся.' },
  { id:18, name:'Datang Tuoketuo Power Plant Extension', nameRu:'ТЭС Датан (доп. блок)', type:'coal',
    lng:111.150, lat:40.250, capacity:2400, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2009, annual:'13 TWh', units:4,
    img: null,
    description:'Additional coal units adjacent to the Tuoketuo complex feeding the North China power grid.',
    descriptionRu:'Дополнительные угольные блоки рядом с комплексом Туокэтуо, питающие энергосистему Северного Китая.' },

  // ── BRAZIL / SOUTH AMERICA ──────────────────────────────────
  { id:20, name:'Itaipu Dam', nameRu:'ГЭС Итайпу', type:'hydro',
    lng:-54.590, lat:-25.408, capacity:14000, country:'Brazil/Paraguay', countryRu:'Бразилия/Парагвай',
    river:'Paraná', riverRu:'Парана', status:'active', year:1984, annual:'96 TWh', units:20,
    img: IMG('Itaipu_Dam.jpg'),
    description:'Second-largest hydroelectric plant in the world by annual generation. Supplies ~15% of Brazil\'s electricity and ~75% of Paraguay\'s total demand.',
    descriptionRu:'Вторая в мире ГЭС по годовой выработке. Обеспечивает ~15% электроэнергии Бразилии и ~75% всего потребления Парагвая.' },
  { id:21, name:'Belo Monte HPP', nameRu:'ГЭС Белу-Монти', type:'hydro',
    lng:-52.415, lat:-3.120, capacity:11233, country:'Brazil', countryRu:'Бразилия',
    river:'Xingu', riverRu:'Шингу', status:'active', year:2016, annual:'39.5 TWh', units:24,
    img: null,
    description:'Third-largest hydroelectric plant in the world. Located in the Amazon basin; its construction was highly controversial due to displacement of indigenous communities.',
    descriptionRu:'Третья по величине ГЭС в мире. Расположена в бассейне Амазонки; строительство вызвало споры из-за переселения коренных народов.' },
  { id:22, name:'Tucuruí Dam', nameRu:'ГЭС Тукуруи', type:'hydro',
    lng:-49.644, lat:-3.833, capacity:8535, country:'Brazil', countryRu:'Бразилия',
    river:'Tocantins', riverRu:'Токантинс', status:'active', year:1984, annual:'21 TWh', units:25,
    img: null,
    description:'First large hydroelectric dam built entirely in the Brazilian Amazon, supplying aluminium smelters and the northern grid.',
    descriptionRu:'Первая крупная ГЭС, построенная целиком в бразильской Амазонии, питает алюминиевые заводы и северную энергосистему.' },
  { id:23, name:'Guri Dam (Simón Bolívar)', nameRu:'ГЭС Гури (Симон Боливар)', type:'hydro',
    lng:-62.998, lat:7.762, capacity:10235, country:'Venezuela', countryRu:'Венесуэла',
    river:'Caroní', riverRu:'Карони', status:'active', year:1986, annual:'46 TWh', units:20,
    img: null,
    description:'Supplies up to 80% of Venezuela\'s electricity. One of the largest hydroelectric plants in the world, on the Caroní River.',
    descriptionRu:'Обеспечивает до 80% электроэнергии Венесуэлы. Одна из крупнейших ГЭС мира на реке Карони.' },
  { id:24, name:'Yacyretá Dam', nameRu:'ГЭС Яситерета', type:'hydro',
    lng:-56.730, lat:-27.480, capacity:3200, country:'Argentina/Paraguay', countryRu:'Аргентина/Парагвай',
    river:'Paraná', riverRu:'Парана', status:'active', year:1998, annual:'19.8 TWh', units:20,
    img: null,
    description:'Binational dam shared between Argentina and Paraguay, second hydroelectric project on the Paraná River after Itaipu.',
    descriptionRu:'Двунациональная плотина Аргентины и Парагвая, второй гидроэнергетический проект на реке Парана после Итайпу.' },
  { id:25, name:'Cerro Dominador CSP', nameRu:'СЭС Серро Доминадор', type:'solar',
    lng:-69.700, lat:-22.900, capacity:210, country:'Chile', countryRu:'Чили',
    river:null, status:'active', year:2021, annual:'1.7 TWh', units:null,
    img: null,
    description:'First concentrated solar power plant with molten-salt storage in Latin America, in the Atacama Desert — the sunniest place on Earth.',
    descriptionRu:'Первая в Латинской Америке СЭС с расплавом солей для накопления энергии, в пустыне Атакама — самом солнечном месте на Земле.' },

  // ── USA ─────────────────────────────────────────────────────
  { id:30, name:'Grand Coulee Dam', nameRu:'Плотина Гранд-Кули', type:'hydro',
    lng:-118.981, lat:47.967, capacity:6809, country:'USA', countryRu:'США',
    river:'Columbia', riverRu:'Колумбия', status:'active', year:1942, annual:'20 TWh', units:33,
    img: IMG('Grand_Coulee_Dam_panoramic_taken_June_2012.jpg'),
    description:'Largest hydroelectric plant in the USA and the largest concrete structure in the country. Powers the Pacific Northwest and played a key role in WWII aluminium production.',
    descriptionRu:'Крупнейшая ГЭС США и наибольшее бетонное сооружение в стране. Питает Тихоокеанский Северо-Запад.' },
  { id:31, name:'Hoover Dam', nameRu:'Плотина Гувера', type:'hydro',
    lng:-114.737, lat:36.016, capacity:2080, country:'USA', countryRu:'США',
    river:'Colorado', riverRu:'Колорадо', status:'active', year:1936, annual:'4 TWh', units:17,
    img: IMG('Hoover_Dam%2C_Nevada.jpg'),
    description:'Iconic arch-gravity dam on the Colorado River, forming Lake Mead — the USA\'s largest reservoir. A National Historic Landmark and major tourism destination.',
    descriptionRu:'Знаменитая арочно-гравитационная плотина на реке Колорадо, создаёт озеро Мид — крупнейшее водохранилище США.' },
  { id:32, name:'Alta Wind Energy Center', nameRu:'Ветропарк Альта', type:'wind',
    lng:-118.570, lat:34.960, capacity:1547, country:'USA', countryRu:'США',
    river:null, status:'active', year:2012, annual:'3.2 TWh', units:600,
    img: null,
    description:'Largest wind farm in the Western Hemisphere at the time of construction. Located in Tehachapi Pass, California, taking advantage of strong, consistent winds.',
    descriptionRu:'Крупнейший ветропарк Западного полушария на момент постройки. Расположен в перевале Техачапи, Калифорния.' },
  { id:33, name:'Solar Star', nameRu:'Солнечная электростанция Solar Star', type:'solar',
    lng:-118.420, lat:35.090, capacity:579, country:'USA', countryRu:'США',
    river:null, status:'active', year:2015, annual:'1.1 TWh', units:null,
    img: null,
    description:'One of the largest photovoltaic power stations in the USA, covering 13 km² in the Mojave Desert. Uses SunPower\'s high-efficiency monocrystalline silicon panels.',
    descriptionRu:'Одна из крупнейших фотовольтаических станций США, занимает 13 км² в пустыне Мохаве. Использует высокоэффективные монокристаллические панели SunPower.' },
  { id:34, name:'Palo Verde Nuclear', nameRu:'АЭС Пало-Верде', type:'nuclear',
    lng:-112.862, lat:33.388, capacity:3937, country:'USA', countryRu:'США',
    river:null, status:'active', year:1988, annual:'32 TWh', units:3,
    img: null,
    description:'Largest nuclear power plant in the United States by output, and the only one not located near a body of water — cooled by treated wastewater.',
    descriptionRu:'Крупнейшая АЭС США по выработке. Единственная, не расположенная у водоёма — охлаждается очищенными сточными водами.' },
  { id:35, name:'Diablo Canyon Power Plant', nameRu:'АЭС Дьябло-Кэньон', type:'nuclear',
    lng:-120.854, lat:35.211, capacity:2256, country:'USA', countryRu:'США',
    river:null, status:'active', year:1985, annual:'18 TWh', units:2,
    img: null,
    description:'California\'s last operating nuclear plant, on the Pacific coast. Originally slated for closure, its life was extended due to grid reliability needs.',
    descriptionRu:'Последняя действующая АЭС Калифорнии на тихоокеанском побережье. Срок эксплуатации продлён из-за потребностей энергосистемы.' },
  { id:36, name:'Chief Joseph Dam', nameRu:'Плотина Чиф-Джозеф', type:'hydro',
    lng:-119.638, lat:48.000, capacity:2620, country:'USA', countryRu:'США',
    river:'Columbia', riverRu:'Колумбия', status:'active', year:1958, annual:'10 TWh', units:27,
    img: null,
    description:'Second-largest power producer among US dams, downstream of Grand Coulee on the Columbia River.',
    descriptionRu:'Вторая по выработке среди плотин США, ниже по течению от Гранд-Кули на реке Колумбия.' },
  { id:37, name:'Robert Moses Niagara Power Plant', nameRu:'ГЭС Роберт Мозес (Ниагара)', type:'hydro',
    lng:-79.040, lat:43.115, capacity:2525, country:'USA', countryRu:'США',
    river:'Niagara', riverRu:'Ниагара', status:'active', year:1961, annual:'8 TWh', units:13,
    img: null,
    description:'Diverts water from above Niagara Falls to generate power, paired with the Canadian Sir Adam Beck stations across the border.',
    descriptionRu:'Отводит воду выше Ниагарского водопада для выработки энергии, работает в паре с канадскими станциями Сэра Адама Бека.' },
  { id:38, name:'Topaz Solar Farm', nameRu:'СЭС Топаз', type:'solar',
    lng:-120.270, lat:35.380, capacity:550, country:'USA', countryRu:'США',
    river:null, status:'active', year:2014, annual:'1.3 TWh', units:null,
    img: null,
    description:'One of the largest thin-film photovoltaic plants in the world when completed, located in San Luis Obispo County, California.',
    descriptionRu:'Одна из крупнейших тонкоплёночных фотовольтаических станций мира на момент завершения, в округе Сан-Луис-Обиспо, Калифорния.' },

  // ── CANADA ──────────────────────────────────────────────────
  { id:70, name:'Bruce Nuclear', nameRu:'АЭС Брюс', type:'nuclear',
    lng:-81.594, lat:44.322, capacity:6430, country:'Canada', countryRu:'Канада',
    river:null, status:'active', year:1977, annual:'47 TWh', units:8,
    img: null,
    description:'Largest nuclear generating facility in the Western Hemisphere. Eight CANDU pressurised heavy-water reactors on the shore of Lake Huron.',
    descriptionRu:'Крупнейший ядерный генерирующий комплекс Западного полушария. Восемь реакторов CANDU с тяжёлой водой на берегу озера Гурон.' },
  { id:71, name:'Robert-Bourassa Generating Station', nameRu:'ГЭС Робер-Буросса', type:'hydro',
    lng:-77.450, lat:53.790, capacity:5616, country:'Canada', countryRu:'Канада',
    river:'La Grande', riverRu:'Ла-Гранд', status:'active', year:1981, annual:'26.5 TWh', units:16,
    img: null,
    description:'The largest underground power station in the world, part of the massive James Bay hydroelectric project in Quebec.',
    descriptionRu:'Крупнейшая подземная электростанция мира, часть масштабного гидроэнергетического проекта Джеймс-Бей в Квебеке.' },
  { id:72, name:'Churchill Falls Generating Station', nameRu:'ГЭС Черчилл-Фолс', type:'hydro',
    lng:-64.000, lat:53.580, capacity:5428, country:'Canada', countryRu:'Канада',
    river:'Churchill', riverRu:'Черчилл', status:'active', year:1971, annual:'35 TWh', units:11,
    img: null,
    description:'One of the largest underground hydroelectric plants in the world, in Labrador, exporting most of its power to Quebec.',
    descriptionRu:'Одна из крупнейших подземных ГЭС мира, в Лабрадоре, экспортирует большую часть энергии в Квебек.' },
  { id:73, name:'W.A.C. Bennett Dam', nameRu:'Плотина У. А. К. Беннетта', type:'hydro',
    lng:-122.150, lat:56.020, capacity:2730, country:'Canada', countryRu:'Канада',
    river:'Peace', riverRu:'Пис', status:'active', year:1968, annual:'13 TWh', units:10,
    img: null,
    description:'Creates Williston Lake, the largest reservoir in British Columbia, and anchors the province\'s hydro grid.',
    descriptionRu:'Создаёт озеро Уиллистон, крупнейшее водохранилище Британской Колумбии, основа гидроэнергетики провинции.' },

  // ── EUROPE ──────────────────────────────────────────────────
  { id:40, name:'Zaporizhzhia NPP', nameRu:'Запорожская АЭС', type:'nuclear',
    lng:34.588, lat:47.510, capacity:5700, country:'Ukraine', countryRu:'Украина',
    river:'Kakhovka Reservoir', riverRu:'Каховское водохр.', status:'active', year:1985, annual:'40 TWh', units:6,
    img: IMG('Zaporizhzhia_NPP_from_Energodar.jpg'),
    description:'Largest nuclear power plant in Europe. Six VVER-1000 reactors. Under Russian military control since March 2022, causing major nuclear safety concerns.',
    descriptionRu:'Крупнейшая атомная электростанция Европы. Шесть реакторов ВВЭР-1000. С марта 2022 года под российским военным контролем.' },
  { id:41, name:'Gravelines Nuclear', nameRu:'АЭС Гравлин', type:'nuclear',
    lng:2.141, lat:51.014, capacity:5706, country:'France', countryRu:'Франция',
    river:'North Sea', riverRu:'Северное море', status:'active', year:1980, annual:'38 TWh', units:6,
    img: null,
    description:'Largest nuclear power plant in Western Europe. Six 950 MW PWR reactors operated by EDF. France generates ~70% of its electricity from nuclear power.',
    descriptionRu:'Крупнейшая АЭС в Западной Европе. Шесть реакторов PWR по 950 МВт. Франция производит ~70% электроэнергии на АЭС.' },
  { id:42, name:'Bełchatów Power Station', nameRu:'ТЭС Белхатув', type:'coal',
    lng:19.330, lat:51.265, capacity:5420, country:'Poland', countryRu:'Польша',
    river:null, status:'active', year:1981, annual:'28 TWh', units:13,
    img: null,
    description:'Largest power plant in the European Union and Europe\'s largest CO₂ emitter. Burns lignite (brown coal) extracted from an adjacent open-cast mine.',
    descriptionRu:'Крупнейшая электростанция Евросоюза и главный эмитент CO₂ в Европе. Сжигает бурый уголь из соседнего открытого разреза.' },
  { id:43, name:'Hornsea 1', nameRu:'Ветропарк Хорнси-1', type:'wind',
    lng:1.650, lat:53.910, capacity:1218, country:'UK', countryRu:'Великобритания',
    river:null, status:'active', year:2019, annual:'4.2 TWh', units:174,
    img: IMG('Hornsea_Wind_Farm_1.jpg'),
    description:'World\'s largest offshore wind farm at time of completion. 174 Siemens Gamesa 7 MW turbines located 120 km off the Yorkshire coast in the North Sea.',
    descriptionRu:'На момент завершения — крупнейший офшорный ветропарк мира. 174 турбины Siemens Gamesa по 7 МВт в 120 км от побережья Йоркшира.' },
  { id:44, name:'Cattenom Nuclear', nameRu:'АЭС Каттеном', type:'nuclear',
    lng:6.218, lat:49.417, capacity:5448, country:'France', countryRu:'Франция',
    river:'Moselle', riverRu:'Мозель', status:'active', year:1986, annual:'36 TWh', units:4,
    img: null,
    description:'Four 1,300 MW reactors near the borders of Luxembourg and Germany, among the largest contributors to French nuclear output.',
    descriptionRu:'Четыре реактора по 1300 МВт near границ Люксембурга и Германии, один из крупнейших вкладчиков в атомную генерацию Франции.' },
  { id:45, name:'Niederaußem Power Station', nameRu:'ТЭС Нидераусем', type:'coal',
    lng:6.660, lat:50.980, capacity:3864, country:'Germany', countryRu:'Германия',
    river:null, status:'active', year:1963, annual:'20 TWh', units:9,
    img: null,
    description:'Major lignite power plant in the Rhenish coalfield, one of the largest CO₂ emitters in Germany.',
    descriptionRu:'Крупная буроугольная электростанция в Рейнском угольном бассейне, один из крупнейших эмитентов CO₂ в Германии.' },
  { id:46, name:'Noor Ouarzazate Solar Complex', nameRu:'Солнечный комплекс Нур-Уарзазат', type:'solar',
    lng:-6.860, lat:30.910, capacity:580, country:'Morocco', countryRu:'Марокко',
    river:null, status:'active', year:2016, annual:'1.5 TWh', units:null,
    img: IMG('Noor_1_Ouarzazate.jpg'),
    description:'One of the largest concentrated solar power complexes in the world, with molten-salt thermal storage allowing electricity generation after sunset.',
    descriptionRu:'Один из крупнейших комплексов концентрированной солнечной энергии в мире, с тепловым накопителем на расплаве солей.' },
  { id:47, name:'Fântânele-Cogealac Wind Farm', nameRu:'Ветропарк Фынтынеле-Когялак', type:'wind',
    lng:28.700, lat:44.690, capacity:600, country:'Romania', countryRu:'Румыния',
    river:null, status:'active', year:2012, annual:'1.3 TWh', units:240,
    img: null,
    description:'Largest onshore wind farm in Europe at the time of completion, located in the Dobrogea plateau near the Black Sea.',
    descriptionRu:'Крупнейший наземный ветропарк Европы на момент завершения, расположен на плато Добруджа у Чёрного моря.' },
  { id:48, name:'Dogger Bank Wind Farm', nameRu:'Ветропарк Доггер-Банк', type:'wind',
    lng:2.500, lat:54.750, capacity:3600, country:'UK', countryRu:'Великобритания',
    river:null, status:'construction', year:2026, annual:'18 TWh', units:277,
    img: null,
    description:'Will be the world\'s largest offshore wind farm upon completion, built in three phases far out in the North Sea.',
    descriptionRu:'После завершения станет крупнейшим офшорным ветропарком мира, строится в три фазы далеко в Северном море.' },
  { id:49, name:'Krsko Nuclear Power Plant', nameRu:'АЭС Кршко', type:'nuclear',
    lng:15.516, lat:45.937, capacity:696, country:'Slovenia', countryRu:'Словения',
    river:'Sava', riverRu:'Сава', status:'active', year:1983, annual:'5.4 TWh', units:1,
    img: null,
    description:'Slovenia\'s only nuclear plant, jointly owned with Croatia, supplies roughly a fifth of Slovenia\'s electricity.',
    descriptionRu:'Единственная АЭС Словении, совместное владение с Хорватией, обеспечивает около пятой части электроэнергии страны.' },
  { id:4001, name:'Olkiluoto Nuclear Power Plant', nameRu:'АЭС Олкилуото', type:'nuclear',
    lng:21.440, lat:61.237, capacity:2780, country:'Finland', countryRu:'Финляндия',
    river:null, status:'active', year:1978, annual:'21 TWh', units:3,
    img: null,
    description:'Includes Olkiluoto 3, Europe\'s first EPR reactor, completed in 2023 after a famously long construction delay.',
    descriptionRu:'Включает Олкилуото-3 — первый в Европе реактор EPR, завершён в 2023 году после знаменитой долгой задержки строительства.' },
  { id:4002, name:'Ringhals Nuclear Power Plant', nameRu:'АЭС Рингхальс', type:'nuclear',
    lng:12.111, lat:57.260, capacity:2190, country:'Sweden', countryRu:'Швеция',
    river:null, status:'active', year:1976, annual:'15 TWh', units:2,
    img: null,
    description:'Historically the largest power plant in the Nordic countries; two of its four original reactors have been decommissioned.',
    descriptionRu:'Исторически крупнейшая электростанция Северной Европы; два из четырёх исходных реакторов выведены из эксплуатации.' },
  { id:4003, name:'Borssele Nuclear Power Station', nameRu:'АЭС Борселе', type:'nuclear',
    lng:3.717, lat:51.434, capacity:482, country:'Netherlands', countryRu:'Нидерланды',
    river:null, status:'active', year:1973, annual:'3.7 TWh', units:1,
    img: null,
    description:'The only operating nuclear power station in the Netherlands, providing about 3% of national electricity.',
    descriptionRu:'Единственная действующая АЭС Нидерландов, обеспечивает около 3% электроэнергии страны.' },
  { id:4004, name:'Kozloduy Nuclear Power Plant', nameRu:'АЭС Козлодуй', type:'nuclear',
    lng:23.770, lat:43.745, capacity:2000, country:'Bulgaria', countryRu:'Болгария',
    river:'Danube', riverRu:'Дунай', status:'active', year:1974, annual:'16 TWh', units:2,
    img: null,
    description:'Generates about a third of Bulgaria\'s electricity from two VVER-1000 reactors on the Danube River.',
    descriptionRu:'Вырабатывает около трети электроэнергии Болгарии на двух реакторах ВВЭР-1000 на реке Дунай.' },
  { id:4005, name:'Paks Nuclear Power Plant', nameRu:'АЭС Пакш', type:'nuclear',
    lng:18.853, lat:46.574, capacity:2000, country:'Hungary', countryRu:'Венгрия',
    river:'Danube', riverRu:'Дунай', status:'active', year:1983, annual:'15.7 TWh', units:4,
    img: null,
    description:'Supplies around half of Hungary\'s domestically generated electricity from four VVER-440 reactors.',
    descriptionRu:'Обеспечивает около половины собственной выработки электроэнергии Венгрии на четырёх реакторах ВВЭР-440.' },
  { id:4006, name:'Dukovany Nuclear Power Plant', nameRu:'АЭС Дукованы', type:'nuclear',
    lng:16.149, lat:49.085, capacity:2040, country:'Czech Republic', countryRu:'Чехия',
    river:null, status:'active', year:1985, annual:'15 TWh', units:4,
    img: null,
    description:'One of two Czech nuclear plants, four VVER-440 reactors providing roughly a fifth of national electricity.',
    descriptionRu:'Одна из двух чешских АЭС, четыре реактора ВВЭР-440 обеспечивают около пятой части электроэнергии страны.' },
  { id:4007, name:'Doel Nuclear Power Station', nameRu:'АЭС Доль', type:'nuclear',
    lng:4.259, lat:51.323, capacity:2911, country:'Belgium', countryRu:'Бельгия',
    river:'Scheldt', riverRu:'Шельда', status:'active', year:1975, annual:'17 TWh', units:4,
    img: null,
    description:'One of Belgium\'s two nuclear sites, on the Scheldt estuary near Antwerp, key to the country\'s low-carbon grid.',
    descriptionRu:'Одна из двух атомных площадок Бельгии, на эстуарии Шельды у Антверпена, ключевой элемент низкоуглеродной энергосистемы страны.' },
  { id:4008, name:'Vandellòs II Nuclear Power Plant', nameRu:'АЭС Вандельос-2', type:'nuclear',
    lng:0.866, lat:40.952, capacity:1087, country:'Spain', countryRu:'Испания',
    river:null, status:'active', year:1988, annual:'8.9 TWh', units:1,
    img: null,
    description:'Coastal nuclear plant on the Costa Dorada in Catalonia, replacing the earlier Vandellòs I gas-graphite reactor.',
    descriptionRu:'Прибрежная АЭС на Коста-Дорада в Каталонии, заменившая прежний газо-графитовый реактор Вандельос-1.' },
  { id:4009, name:'Núñez de Balboa Solar Plant', nameRu:'СЭС Нуньес-де-Бальбоа', type:'solar',
    lng:-6.286, lat:38.770, capacity:500, country:'Spain', countryRu:'Испания',
    river:null, status:'active', year:2020, annual:'0.87 TWh', units:null,
    img: null,
    description:'One of the largest photovoltaic plants in Europe, located in Extremadura, a region with some of the continent\'s highest solar irradiance.',
    descriptionRu:'Одна из крупнейших фотовольтаических станций Европы, расположена в Эстремадуре — регионе с самой высокой солнечной инсоляцией на континенте.' },
  { id:4010, name:'Whitelee Wind Farm', nameRu:'Ветропарк Уайтли', type:'wind',
    lng:-4.350, lat:55.660, capacity:539, country:'UK', countryRu:'Великобритания',
    river:null, status:'active', year:2009, annual:'1.1 TWh', units:215,
    img: null,
    description:'Largest onshore wind farm in the UK, located on a former forest plantation south of Glasgow, Scotland.',
    descriptionRu:'Крупнейший наземный ветропарк Великобритании, расположен на месте бывшей лесопосадки к югу от Глазго, Шотландия.' },
  { id:4011, name:'London Array', nameRu:'Ветропарк Лондон-Аррэй', type:'wind',
    lng:1.500, lat:51.633, capacity:630, country:'UK', countryRu:'Великобритания',
    river:null, status:'active', year:2013, annual:'2.1 TWh', units:175,
    img: null,
    description:'One of the world\'s largest offshore wind farms at the time, in the outer Thames Estuary.',
    descriptionRu:'Один из крупнейших офшорных ветропарков мира на момент постройки, во внешнем устье Темзы.' },
  { id:4012, name:'Anholt Offshore Wind Farm', nameRu:'Ветропарк Анхольт', type:'wind',
    lng:11.220, lat:56.600, capacity:400, country:'Denmark', countryRu:'Дания',
    river:null, status:'active', year:2013, annual:'1.4 TWh', units:111,
    img: null,
    description:'One of the largest offshore wind farms in Denmark, a country deriving nearly half its electricity from wind.',
    descriptionRu:'Один из крупнейших офшорных ветропарков Дании — страны, получающей почти половину электроэнергии от ветра.' },

  // ── RUSSIA ──────────────────────────────────────────────────
  { id:50, name:'Krasnoyarsk HPP', nameRu:'Красноярская ГЭС', type:'hydro',
    lng:92.424, lat:55.972, capacity:6000, country:'Russia', countryRu:'Россия',
    river:'Yenisei', riverRu:'Енисей', status:'active', year:1967, annual:'18 TWh', units:12,
    img: null,
    description:'One of the most powerful hydroelectric plants in Russia. Features the unique Krasnoyarsk ship lift, allowing vessels to bypass the 124 m dam.',
    descriptionRu:'Одна из мощнейших ГЭС России. Единственная в России судоподъёмная машина позволяет судам обходить 124-метровую плотину.' },
  { id:51, name:'Leningrad NPP', nameRu:'Ленинградская АЭС', type:'nuclear',
    lng:29.068, lat:59.838, capacity:4200, country:'Russia', countryRu:'Россия',
    river:null, status:'active', year:1974, annual:'28 TWh', units:6,
    img: null,
    description:'One of Russia\'s oldest nuclear power plants. The original four RBMK-1000 reactors (same type as Chernobyl) are being replaced by new VVER-1200 units.',
    descriptionRu:'Одна из старейших АЭС России. Четыре исходных реактора РБМК-1000 (того же типа, что в Чернобыле) заменяются новыми ВВЭР-1200.' },
  { id:52, name:'Surgut-2 GRES', nameRu:'Сургутская ГРЭС-2', type:'gas',
    lng:73.514, lat:61.240, capacity:5597, country:'Russia', countryRu:'Россия',
    river:null, status:'active', year:1985, annual:'35 TWh', units:6,
    img: null,
    description:'World\'s largest natural gas-fired power station. Supplies electricity to the Urals, Western Siberia, and Tyumen regions. Burns associated petroleum gas.',
    descriptionRu:'Крупнейшая в мире газовая электростанция. Снабжает Урал, Западную Сибирь и Тюменский регион. Сжигает попутный нефтяной газ.' },
  { id:53, name:'Sayano-Shushenskaya HPP', nameRu:'Саяно-Шушенская ГЭС', type:'hydro',
    lng:91.388, lat:52.789, capacity:6400, country:'Russia', countryRu:'Россия',
    river:'Yenisei', riverRu:'Енисей', status:'active', year:1978, annual:'23 TWh', units:10,
    img: null,
    description:'Largest power plant in Russia by installed capacity, on the Yenisei River. Site of a fatal 2009 turbine accident, fully rebuilt by 2017.',
    descriptionRu:'Крупнейшая электростанция России по установленной мощности, на реке Енисей. Место аварии 2009 года, полностью восстановлена к 2017 году.' },
  { id:54, name:'Bratsk HPP', nameRu:'Братская ГЭС', type:'hydro',
    lng:101.700, lat:56.233, capacity:4500, country:'Russia', countryRu:'Россия',
    river:'Angara', riverRu:'Ангара', status:'active', year:1967, annual:'22 TWh', units:18,
    img: null,
    description:'On the Angara River in Siberia, powers one of the world\'s largest aluminium smelters in Bratsk.',
    descriptionRu:'На реке Ангара в Сибири, питает один из крупнейших в мире алюминиевых заводов в Братске.' },
  { id:55, name:'Balakovo NPP', nameRu:'Балаковская АЭС', type:'nuclear',
    lng:47.998, lat:52.090, capacity:4000, country:'Russia', countryRu:'Россия',
    river:'Volga', riverRu:'Волга', status:'active', year:1985, annual:'30 TWh', units:4,
    img: null,
    description:'Four VVER-1000 reactors on the Volga River, one of the largest single nuclear sites in Russia.',
    descriptionRu:'Четыре реактора ВВЭР-1000 на реке Волга, одна из крупнейших атомных площадок России.' },

  // ── JAPAN ───────────────────────────────────────────────────
  { id:60, name:'Kashiwazaki-Kariwa NPP', nameRu:'АЭС Касивадзаки-Карива', type:'nuclear',
    lng:138.603, lat:37.432, capacity:7965, country:'Japan', countryRu:'Япония',
    river:null, status:'active', year:1985, annual:'0 TWh', units:7,
    img: IMG('Kashiwazaki-Kariwa_Nuclear_Power_Plant.jpg'),
    description:'World\'s largest nuclear power plant by installed capacity. All 7 reactors have been offline since the 2011 Fukushima disaster. Restart approval granted for 2 units in 2023.',
    descriptionRu:'Крупнейшая АЭС в мире по установленной мощности. Все 7 реакторов остановлены после Фукусимы в 2011 г. В 2023 г. получено разрешение на перезапуск 2 блоков.' },
  { id:61, name:'Futtsu Power Station', nameRu:'ТЭС Фуцу', type:'gas',
    lng:139.825, lat:35.310, capacity:5040, country:'Japan', countryRu:'Япония',
    river:null, status:'active', year:1985, annual:'25 TWh', units:24,
    img: null,
    description:'One of the world\'s largest LNG combined-cycle power stations, on Tokyo Bay, run by JERA.',
    descriptionRu:'Одна из крупнейших в мире газовых электростанций на СПГ комбинированного цикла, на Токийском заливе, оператор JERA.' },
  { id:62, name:'Kurobe Dam', nameRu:'Плотина Куробе', type:'hydro',
    lng:137.667, lat:36.567, capacity:335, country:'Japan', countryRu:'Япония',
    river:'Kurobe', riverRu:'Куробе', status:'active', year:1963, annual:'1 TWh', units:4,
    img: null,
    description:'Japan\'s tallest dam, built in the Northern Alps under extremely difficult conditions; a major tourist attraction.',
    descriptionRu:'Самая высокая плотина Японии, построена в Северных Альпах в крайне сложных условиях; популярная туристическая достопримечательность.' },

  // ── INDIA ───────────────────────────────────────────────────
  { id:80, name:'Vindhyachal Super TPS', nameRu:'ТЭС Виндхьячал', type:'coal',
    lng:82.667, lat:23.980, capacity:4760, country:'India', countryRu:'Индия',
    river:null, status:'active', year:1987, annual:'26 TWh', units:8,
    img: null,
    description:'Largest coal-fired power plant in India. Located in Madhya Pradesh, on the banks of the Rihand reservoir. Supplies electricity to northern India.',
    descriptionRu:'Крупнейшая угольная электростанция Индии. Расположена в Мадхья-Прадеше на берегу водохранилища Риханд.' },
  { id:81, name:'Bhadla Solar Park', nameRu:'Солнечный парк Бхадла', type:'solar',
    lng:71.906, lat:27.541, capacity:2245, country:'India', countryRu:'Индия',
    river:null, status:'active', year:2020, annual:'5.5 TWh', units:null,
    img: IMG('Bhadla_Solar_Park.jpg'),
    description:'World\'s largest solar park by installed capacity. Located in the Thar Desert, Rajasthan, where temperatures exceed 50°C. Covers over 56 km².',
    descriptionRu:'Крупнейший в мире солнечный парк по установленной мощности. Расположен в пустыне Тар (Раджастхан) при температурах свыше 50°C. Площадь — более 56 км².' },
  { id:82, name:'Muppandal Wind Farm', nameRu:'Ветропарк Муппандал', type:'wind',
    lng:77.650, lat:8.240, capacity:1500, country:'India', countryRu:'Индия',
    river:null, status:'active', year:1996, annual:'3 TWh', units:3000,
    img: null,
    description:'Largest wind farm in India, located at the southern tip of the subcontinent in Tamil Nadu. Takes advantage of strong monsoon-driven winds.',
    descriptionRu:'Крупнейший ветропарк Индии, расположен на южной оконечности субконтинента в Тамилнаду. Использует сильные муссонные ветры.' },
  { id:83, name:'Tehri Dam', nameRu:'Плотина Тхери', type:'hydro',
    lng:78.480, lat:30.378, capacity:2400, country:'India', countryRu:'Индия',
    river:'Bhagirathi', riverRu:'Бхагиратхи', status:'active', year:2006, annual:'2.6 TWh', units:5,
    img: null,
    description:'One of the tallest dams in the world, in Uttarakhand, also providing irrigation and drinking water to northern India.',
    descriptionRu:'Одна из самых высоких плотин мира, в штате Уттаракханд, также обеспечивает ирригацию и питьевую воду для севера Индии.' },
  { id:84, name:'Bhakra Dam', nameRu:'Плотина Бхакра', type:'hydro',
    lng:76.430, lat:31.412, capacity:1325, country:'India', countryRu:'Индия',
    river:'Sutlej', riverRu:'Сатледж', status:'active', year:1963, annual:'6 TWh', units:10,
    img: null,
    description:'One of the highest gravity dams in Asia, called the "Temple of Modern India" by Nehru, irrigates Punjab, Haryana, and Rajasthan.',
    descriptionRu:'Одна из самых высоких гравитационных плотин Азии, названная Неру «храмом современной Индии», обеспечивает ирригацию Пенджаба, Харьяны и Раджастхана.' },
  { id:85, name:'Sasan Ultra Mega Power Plant', nameRu:'ТЭС Сасан (Ultra Mega)', type:'coal',
    lng:82.300, lat:24.130, capacity:3960, country:'India', countryRu:'Индия',
    river:null, status:'active', year:2013, annual:'24 TWh', units:6,
    img: null,
    description:'One of India\'s "Ultra Mega" coal projects with an integrated captive coal mine, in Madhya Pradesh.',
    descriptionRu:'Один из «ультра-мега» угольных проектов Индии с собственной угольной шахтой, в штате Мадхья-Прадеш.' },
  { id:86, name:'Jaisalmer Wind Park', nameRu:'Ветропарк Джайсалмер', type:'wind',
    lng:70.900, lat:26.900, capacity:1064, country:'India', countryRu:'Индия',
    river:null, status:'active', year:2001, annual:'2.1 TWh', units:2000,
    img: null,
    description:'Major wind power cluster in the Thar Desert of Rajasthan, developed by Suzlon Energy.',
    descriptionRu:'Крупный кластер ветроэнергетики в пустыне Тар, штат Раджастхан, разработан компанией Suzlon Energy.' },
  { id:87, name:'Kudankulam Nuclear Power Plant', nameRu:'АЭС Куданкулам', type:'nuclear',
    lng:77.715, lat:8.164, capacity:2000, country:'India', countryRu:'Индия',
    river:null, status:'active', year:2013, annual:'13 TWh', units:2,
    img: null,
    description:'India\'s largest nuclear power station, built with Russian (Rosatom) assistance using VVER-1000 reactors, with further units planned.',
    descriptionRu:'Крупнейшая АЭС Индии, построена с российской помощью (Росатом) с реакторами ВВЭР-1000, планируются дополнительные блоки.' },
  { id:88, name:'Pavagada Solar Park', nameRu:'Солнечный парк Павагада', type:'solar',
    lng:77.280, lat:14.100, capacity:2050, country:'India', countryRu:'Индия',
    river:null, status:'active', year:2019, annual:'4.5 TWh', units:null,
    img: null,
    description:'One of the world\'s largest solar parks, built on semi-arid leased farmland in Karnataka, benefiting local landowners through lease payments.',
    descriptionRu:'Один из крупнейших солнечных парков мира, построен на засушливых арендованных землях в штате Карнатака.' },

  // ── PAKISTAN / BANGLADESH ───────────────────────────────────
  { id:89, name:'Tarbela Dam', nameRu:'Плотина Тарбела', type:'hydro',
    lng:72.700, lat:34.090, capacity:4888, country:'Pakistan', countryRu:'Пакистан',
    river:'Indus', riverRu:'Инд', status:'active', year:1976, annual:'13 TWh', units:18,
    img: null,
    description:'One of the largest earth-filled dams in the world, on the Indus River, central to Pakistan\'s irrigation and power systems.',
    descriptionRu:'Одна из крупнейших земляных плотин мира, на реке Инд, ключевой элемент ирригационной и энергетической систем Пакистана.' },
  { id:8901, name:'Mangla Dam', nameRu:'Плотина Мангла', type:'hydro',
    lng:73.640, lat:33.130, capacity:1310, country:'Pakistan', countryRu:'Пакистан',
    river:'Jhelum', riverRu:'Джелам', status:'active', year:1967, annual:'5.6 TWh', units:10,
    img: null,
    description:'One of the largest dams in the world by structural volume, on the Jhelum River near Kashmir.',
    descriptionRu:'Одна из крупнейших плотин мира по объёму конструкции, на реке Джелам близ Кашмира.' },
  { id:8902, name:'Rooppur Nuclear Power Plant', nameRu:'АЭС Руппур', type:'nuclear',
    lng:89.047, lat:24.058, capacity:2400, country:'Bangladesh', countryRu:'Бангладеш',
    river:'Padma', riverRu:'Падма', status:'construction', year:2025, annual:'18 TWh', units:2,
    img: null,
    description:'Bangladesh\'s first nuclear power plant, built with Russian (Rosatom) assistance using VVER-1200 reactors.',
    descriptionRu:'Первая АЭС Бангладеша, строится с российской помощью (Росатом) на реакторах ВВЭР-1200.' },

  // ── AFRICA / MIDDLE EAST ────────────────────────────────────
  { id:90, name:'Aswan High Dam', nameRu:'Асуанская ГЭС', type:'hydro',
    lng:32.877, lat:23.971, capacity:2100, country:'Egypt', countryRu:'Египет',
    river:'Nile', riverRu:'Нил', status:'active', year:1970, annual:'10 TWh', units:12,
    img: IMG('Aswan_Dam.jpg'),
    description:'Built with Soviet assistance in 1970. Created Lake Nasser, one of the world\'s largest man-made lakes (5,250 km²). Transformed Egyptian agriculture.',
    descriptionRu:'Построена с советской помощью в 1970 г. Создала озеро Насер — одно из крупнейших искусственных озёр мира (5250 км²).' },
  { id:91, name:'Mohammed bin Rashid Al Maktoum Solar Park', nameRu:'Солнечный парк им. Мухаммеда бин Рашида', type:'solar',
    lng:55.370, lat:24.870, capacity:5000, country:'UAE', countryRu:'ОАЭ',
    river:null, status:'active', year:2013, annual:'10.8 TWh', units:null,
    img: null,
    description:'World\'s largest single-site solar park, located in the Dubai desert. Will reach 5,000 MW across multiple phases. Includes CSP, PV, and floating solar technologies.',
    descriptionRu:'Крупнейший в мире солнечный парк на одной площадке, в пустыне Дубая. Достигнет 5000 МВт в нескольких фазах.' },
  { id:92, name:'Kendal Power Station', nameRu:'ТЭС Кендал', type:'coal',
    lng:29.143, lat:-26.092, capacity:4116, country:'South Africa', countryRu:'ЮАР',
    river:null, status:'active', year:1988, annual:'20 TWh', units:6,
    img: null,
    description:'One of the largest coal power stations in Africa. Located in Mpumalanga Province, part of South Africa\'s coal-dominated energy mix which causes severe regional air pollution.',
    descriptionRu:'Одна из крупнейших угольных электростанций Африки. Расположена в провинции Мпумаланга.' },
  { id:93, name:'Medupi Power Station', nameRu:'ТЭС Медупи', type:'coal',
    lng:27.553, lat:-23.687, capacity:4764, country:'South Africa', countryRu:'ЮАР',
    river:null, status:'active', year:2015, annual:'24 TWh', units:6,
    img: null,
    description:'One of the largest dry-cooled coal power stations in the world, plagued by construction delays and design defects.',
    descriptionRu:'Одна из крупнейших угольных электростанций мира с сухим охлаждением, страдала от задержек строительства и конструктивных дефектов.' },
  { id:94, name:'Koeberg Nuclear Power Station', nameRu:'АЭС Кёберг', type:'nuclear',
    lng:18.433, lat:-33.674, capacity:1860, country:'South Africa', countryRu:'ЮАР',
    river:null, status:'active', year:1984, annual:'13 TWh', units:2,
    img: null,
    description:'The only nuclear power plant on the African continent (besides Egypt\'s El Dabaa under construction), near Cape Town.',
    descriptionRu:'Единственная действующая АЭС на африканском континенте (кроме строящейся Эль-Дабаа в Египте), близ Кейптауна.' },
  { id:95, name:'Kariba Dam', nameRu:'Плотина Кариба', type:'hydro',
    lng:28.761, lat:-16.522, capacity:2160, country:'Zambia/Zimbabwe', countryRu:'Замбия/Зимбабве',
    river:'Zambezi', riverRu:'Замбези', status:'active', year:1960, annual:'10.5 TWh', units:12,
    img: IMG('Kariba_Dam_2010.jpg'),
    description:'Forms Lake Kariba, the world\'s largest man-made reservoir by volume. Shared between Zambia and Zimbabwe, with power stations on both banks.',
    descriptionRu:'Создаёт озеро Кариба — крупнейшее по объёму искусственное водохранилище мира. Общее для Замбии и Зимбабве.' },
  { id:96, name:'Cahora Bassa Dam', nameRu:'Плотина Кабора-Баса', type:'hydro',
    lng:32.690, lat:-15.585, capacity:2075, country:'Mozambique', countryRu:'Мозамбик',
    river:'Zambezi', riverRu:'Замбези', status:'active', year:1974, annual:'14 TWh', units:5,
    img: null,
    description:'One of the largest hydroelectric dams in Africa, most of its output exported to South Africa via high-voltage DC lines.',
    descriptionRu:'Одна из крупнейших ГЭС Африки, большая часть выработки экспортируется в ЮАР по линиям постоянного тока высокого напряжения.' },
  { id:97, name:'Akosombo Dam', nameRu:'Плотина Акосомбо', type:'hydro',
    lng:0.060, lat:6.300, capacity:1020, country:'Ghana', countryRu:'Гана',
    river:'Volta', riverRu:'Вольта', status:'active', year:1965, annual:'6 TWh', units:6,
    img: null,
    description:'Created Lake Volta, the largest reservoir by surface area in the world. Historically the backbone of Ghana\'s power supply.',
    descriptionRu:'Создала озеро Вольта — крупнейшее по площади водохранилище мира. Исторически основа энергоснабжения Ганы.' },
  { id:98, name:'Inga II Dam', nameRu:'Плотина Инга II', type:'hydro',
    lng:13.600, lat:-5.520, capacity:1424, country:'DR Congo', countryRu:'ДР Конго',
    river:'Congo', riverRu:'Конго', status:'active', year:1982, annual:'5 TWh', units:8,
    img: null,
    description:'Part of the Inga Falls hydroelectric complex, exploiting only a small fraction of the Congo River\'s vast potential.',
    descriptionRu:'Часть гидроэнергетического комплекса Инга, использует лишь малую часть огромного потенциала реки Конго.' },
  { id:99, name:'Benban Solar Park', nameRu:'Солнечный парк Бенбан', type:'solar',
    lng:32.700, lat:24.480, capacity:1650, country:'Egypt', countryRu:'Египет',
    river:null, status:'active', year:2019, annual:'3.8 TWh', units:null,
    img: null,
    description:'One of the largest solar parks in the world, in Upper Egypt near Aswan, developed with international financing.',
    descriptionRu:'Один из крупнейших солнечных парков мира, в Верхнем Египте близ Асуана, построен на международном финансировании.' },
  { id:9901, name:'Barakah Nuclear Power Plant', nameRu:'АЭС Барака', type:'nuclear',
    lng:52.225, lat:24.011, capacity:5380, country:'UAE', countryRu:'ОАЭ',
    river:null, status:'active', year:2021, annual:'40 TWh', units:4,
    img: null,
    description:'The Arab world\'s first nuclear power plant, built with South Korean technology, supplying a quarter of the UAE\'s electricity.',
    descriptionRu:'Первая АЭС в арабском мире, построена по южнокорейской технологии, обеспечивает четверть электроэнергии ОАЭ.' },
  { id:9902, name:'Shuaibah Power Plant', nameRu:'ТЭС Шуайба', type:'gas',
    lng:39.270, lat:20.450, capacity:5600, country:'Saudi Arabia', countryRu:'Саудовская Аравия',
    river:null, status:'active', year:1989, annual:'30 TWh', units:null,
    img: null,
    description:'Major oil-and-gas-fired power and desalination complex on the Red Sea coast, one of the largest in the Gulf.',
    descriptionRu:'Крупный нефтегазовый энерго-опреснительный комплекс на побережье Красного моря, один из крупнейших в Персидском заливе.' },
  { id:9903, name:'Karun-3 Dam', nameRu:'Плотина Карун-3', type:'hydro',
    lng:50.510, lat:31.840, capacity:2000, country:'Iran', countryRu:'Иран',
    river:'Karun', riverRu:'Карун', status:'active', year:2005, annual:'4.3 TWh', units:8,
    img: null,
    description:'One of the tallest concrete-faced dams in the world, part of a cascade of hydroelectric dams on the Karun River.',
    descriptionRu:'Одна из самых высоких плотин с бетонной облицовкой в мире, часть каскада ГЭС на реке Карун.' },
  { id:9904, name:'Bushehr Nuclear Power Plant', nameRu:'АЭС Бушер', type:'nuclear',
    lng:50.886, lat:28.829, capacity:1000, country:'Iran', countryRu:'Иран',
    river:null, status:'active', year:2011, annual:'7 TWh', units:1,
    img: null,
    description:'Iran\'s first nuclear power plant, built with Russian (Rosatom) assistance on the Persian Gulf coast.',
    descriptionRu:'Первая АЭС Ирана, построена с российской помощью (Росатом) на побережье Персидского залива.' },

  // ── CENTRAL ASIA & CAUCASUS ─────────────────────────────────
  { id:100, name:'Toktogul HPP', nameRu:'Токтогульская ГЭС', type:'hydro',
    lng:73.150, lat:41.870, capacity:1200, country:'Kyrgyzstan', countryRu:'Кыргызстан',
    river:'Naryn', riverRu:'Нарын', status:'active', year:1975, annual:'4.4 TWh', units:4,
    img: null,
    description:'Largest hydroelectric plant in Kyrgyzstan, on the Naryn River, regulating water for the whole Syr Darya basin.',
    descriptionRu:'Крупнейшая ГЭС Кыргызстана, на реке Нарын, регулирует водоток для всего бассейна Сырдарьи.' },
  { id:101, name:'Charvak HPP', nameRu:'Чарвакская ГЭС', type:'hydro',
    lng:70.110, lat:41.620, capacity:600, country:'Uzbekistan', countryRu:'Узбекистан',
    river:'Chirchiq', riverRu:'Чирчик', status:'active', year:1977, annual:'1.6 TWh', units:4,
    img: null,
    description:'Largest HPP in Uzbekistan, on a tributary of the Syr Darya, also forming a popular reservoir resort near Tashkent.',
    descriptionRu:'Крупнейшая ГЭС Узбекистана, на притоке Сырдарьи, также образует популярную зону отдыха у водохранилища близ Ташкента.' },
  { id:102, name:'Mingachevir HPP', nameRu:'Мингячевирская ГЭС', type:'hydro',
    lng:47.020, lat:40.790, capacity:401, country:'Azerbaijan', countryRu:'Азербайджан',
    river:'Kura', riverRu:'Кура', status:'active', year:1953, annual:'1.2 TWh', units:5,
    img: null,
    description:'Largest reservoir and hydroelectric plant in Azerbaijan, on the Kura River, often called the "Azerbaijani Sea".',
    descriptionRu:'Крупнейшее водохранилище и ГЭС Азербайджана, на реке Кура, часто называемое «Азербайджанским морем».' },
  { id:103, name:'Inguri HPP', nameRu:'Ингурская ГЭС', type:'hydro',
    lng:42.110, lat:42.800, capacity:1300, country:'Georgia', countryRu:'Грузия',
    river:'Inguri', riverRu:'Ингури', status:'active', year:1978, annual:'4.5 TWh', units:5,
    img: null,
    description:'Holds the world\'s second-highest arch dam (271.5 m). Provides nearly half of Georgia\'s electricity, partly shared with Abkhazia.',
    descriptionRu:'Вторая по высоте арочная плотина мира (271,5 м). Обеспечивает почти половину электроэнергии Грузии, частично используется Абхазией.' },
  { id:104, name:'Sevan-Hrazdan Cascade', nameRu:'Севан-Раздан каскад ГЭС', type:'hydro',
    lng:44.660, lat:40.430, capacity:561, country:'Armenia', countryRu:'Армения',
    river:'Hrazdan', riverRu:'Раздан', status:'active', year:1959, annual:'1 TWh', units:6,
    img: null,
    description:'A cascade of six hydropower stations regulating outflow from Lake Sevan, Armenia\'s largest lake.',
    descriptionRu:'Каскад из шести ГЭС, регулирующих сток из озера Севан — крупнейшего озера Армении.' },
  { id:105, name:'Metsamor Nuclear Power Plant', nameRu:'Армянская АЭС (Мецамор)', type:'nuclear',
    lng:44.149, lat:40.180, capacity:407, country:'Armenia', countryRu:'Армения',
    river:null, status:'active', year:1980, annual:'2.5 TWh', units:1,
    img: null,
    description:'Armenia\'s only nuclear plant, supplying around 30-40% of national electricity despite seismic risk concerns.',
    descriptionRu:'Единственная АЭС Армении, обеспечивает 30-40% электроэнергии страны, несмотря на сейсмические риски.' },

  // ── SOUTHEAST ASIA / OCEANIA ─────────────────────────────────
  { id:110, name:'Suralaya Power Station', nameRu:'ТЭС Суралая', type:'coal',
    lng:105.917, lat:-5.900, capacity:4025, country:'Indonesia', countryRu:'Индонезия',
    river:null, status:'active', year:1984, annual:'22 TWh', units:8,
    img: null,
    description:'Largest power plant in Indonesia, located on the Sunda Strait coast of Java, key to powering the Java-Bali grid.',
    descriptionRu:'Крупнейшая электростанция Индонезии, на побережье Зондского пролива на Яве, ключевая для энергосистемы Ява-Бали.' },
  { id:111, name:'Mae Moh Power Plant', nameRu:'ТЭС Мае-Мох', type:'coal',
    lng:99.710, lat:18.300, capacity:2400, country:'Thailand', countryRu:'Таиланд',
    river:null, status:'active', year:1978, annual:'15 TWh', units:10,
    img: null,
    description:'Thailand\'s largest lignite power plant, in Lampang Province, paired with the country\'s largest open-pit coal mine.',
    descriptionRu:'Крупнейшая буроугольная электростанция Таиланда, в провинции Лампанг, рядом с крупнейшим открытым угольным разрезом страны.' },
  { id:112, name:'Greater Changhua Offshore Wind Farm', nameRu:'Ветропарк Чанхуа', type:'wind',
    lng:120.000, lat:23.950, capacity:900, country:'Taiwan', countryRu:'Тайвань',
    river:null, status:'active', year:2022, annual:'3.5 TWh', units:111,
    img: null,
    description:'One of the largest offshore wind projects in Asia, in the Taiwan Strait, central to Taiwan\'s renewable energy push.',
    descriptionRu:'Один из крупнейших офшорных ветропроектов Азии, в Тайваньском проливе, ключевой для возобновляемой энергетики Тайваня.' },
  { id:113, name:'Hwacheon Dam', nameRu:'Плотина Хвачхон', type:'hydro',
    lng:127.700, lat:38.130, capacity:108, country:'South Korea', countryRu:'Южная Корея',
    river:'Bukhan', riverRu:'Пукханган', status:'active', year:1944, annual:'0.3 TWh', units:4,
    img: null,
    description:'One of South Korea\'s oldest hydroelectric dams, strategically fought over during the Korean War.',
    descriptionRu:'Одна из старейших ГЭС Южной Кореи, объект стратегических боёв во время Корейской войны.' },
  { id:114, name:'Manapouri Power Station', nameRu:'ГЭС Манапури', type:'hydro',
    lng:167.700, lat:-45.470, capacity:850, country:'New Zealand', countryRu:'Новая Зеландия',
    river:'Waiau', riverRu:'Вайау', status:'active', year:1971, annual:'5 TWh', units:7,
    img: null,
    description:'New Zealand\'s largest hydroelectric power station, built underground in Fiordland to supply an aluminium smelter.',
    descriptionRu:'Крупнейшая ГЭС Новой Зеландии, построена подземно в Фьордленде для снабжения алюминиевого завода.' },
  { id:115, name:'Hazelwood Power Station Site Wind Repower', nameRu:'Ветропарк на месте ТЭС Хейзелвуд', type:'wind',
    lng:146.420, lat:-38.270, capacity:300, country:'Australia', countryRu:'Австралия',
    river:null, status:'construction', year:2026, annual:'1 TWh', units:50,
    img: null,
    description:'A renewable energy project replacing a decommissioned brown coal plant in Victoria\'s Latrobe Valley.',
    descriptionRu:'Проект возобновляемой энергетики, заменяющий выведенную из эксплуатации буроугольную ТЭС в долине Латроб, штат Виктория.' },
  { id:116, name:'Bayan Obo / Mongolia Wind Corridor', nameRu:'Ветрокоридор Внутренней Монголии', type:'wind',
    lng:109.950, lat:40.580, capacity:1000, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2015, annual:'2.2 TWh', units:500,
    img: null,
    description:'Part of the broader Inner Mongolia wind power buildout supplying electricity to eastern Chinese provinces via UHV lines.',
    descriptionRu:'Часть масштабного развития ветроэнергетики Внутренней Монголии, питает восточные провинции Китая по линиям СВН.' },

  // ── TURKEY ──────────────────────────────────────────────────
  { id:120, name:'Atatürk Dam', nameRu:'Плотина Ататюрка', type:'hydro',
    lng:38.280, lat:37.480, capacity:2400, country:'Turkey', countryRu:'Турция',
    river:'Euphrates', riverRu:'Евфрат', status:'active', year:1990, annual:'8.9 TWh', units:8,
    img: IMG('Ataturk_Dam.jpg'),
    description:'One of the largest dams in the world, centrepiece of the Southeastern Anatolia Project (GAP) on the Euphrates River.',
    descriptionRu:'Одна из крупнейших плотин мира, центральный элемент Юго-Восточного Анатолийского проекта (GAP) на реке Евфрат.' },
  { id:121, name:'Akkuyu Nuclear Power Plant', nameRu:'АЭС Аккую', type:'nuclear',
    lng:33.540, lat:36.150, capacity:4800, country:'Turkey', countryRu:'Турция',
    river:null, status:'construction', year:2025, annual:'35 TWh', units:4,
    img: null,
    description:'Turkey\'s first nuclear power plant, built and financed by Russia\'s Rosatom on the Mediterranean coast.',
    descriptionRu:'Первая АЭС Турции, строится и финансируется российской компанией Росатом на средиземноморском побережье.' },

  // ── KAZAKHSTAN / MONGOLIA ─────────────────────────────────────
  { id:130, name:'Ekibastuz GRES-1', nameRu:'Экибастузская ГРЭС-1', type:'coal',
    lng:75.450, lat:51.700, capacity:4000, country:'Kazakhstan', countryRu:'Казахстан',
    river:null, status:'active', year:1980, annual:'18 TWh', units:8,
    img: null,
    description:'One of the largest coal-fired power stations in Central Asia, burning low-grade local coal in northeastern Kazakhstan.',
    descriptionRu:'Одна из крупнейших угольных электростанций Центральной Азии, сжигает местный низкосортный уголь на северо-востоке Казахстана.' },
  { id:131, name:'Moinak HPP', nameRu:'Мойнакская ГЭС', type:'hydro',
    lng:79.300, lat:43.250, capacity:300, country:'Kazakhstan', countryRu:'Казахстан',
    river:'Charyn', riverRu:'Чарын', status:'active', year:2012, annual:'0.9 TWh', units:2,
    img: null,
    description:'A modern hydroelectric station on the Charyn River, helping diversify Kazakhstan\'s coal-heavy energy mix.',
    descriptionRu:'Современная ГЭС на реке Чарын, помогает диверсифицировать энергобаланс Казахстана, основанный на угле.' },

  // ── MORE WIND / SOLAR ICONS WORLDWIDE ──────────────────────
  { id:140, name:'Walney Extension Offshore Wind Farm', nameRu:'Ветропарк Уолни-Экстеншн', type:'wind',
    lng:-3.530, lat:54.040, capacity:659, country:'UK', countryRu:'Великобритания',
    river:null, status:'active', year:2018, annual:'2 TWh', units:87,
    img: null,
    description:'One of the world\'s largest offshore wind farms at completion, in the Irish Sea off Cumbria.',
    descriptionRu:'Один из крупнейших офшорных ветропарков мира на момент завершения, в Ирландском море у побережья Камбрии.' },
  { id:141, name:'Ivanpah Solar Power Facility', nameRu:'СЭС Айванпа', type:'solar',
    lng:-115.470, lat:35.560, capacity:392, country:'USA', countryRu:'США',
    river:null, status:'active', year:2014, annual:'0.65 TWh', units:null,
    img: IMG('Ivanpah_Solar_Power_Facility_2014.jpg'),
    description:'One of the largest concentrated solar thermal power plants in the world, in the Mojave Desert near the California-Nevada border.',
    descriptionRu:'Одна из крупнейших станций концентрированной солнечной тепловой энергии в мире, в пустыне Мохаве у границы Калифорнии и Невады.' },
  { id:142, name:'Al Dhafra Solar PV Plant', nameRu:'СЭС Аль-Дафра', type:'solar',
    lng:54.500, lat:23.700, capacity:2100, country:'UAE', countryRu:'ОАЭ',
    river:null, status:'active', year:2023, annual:'4.2 TWh', units:null,
    img: null,
    description:'One of the world\'s largest single-site solar plants, using bifacial panels with single-axis tracking near Abu Dhabi.',
    descriptionRu:'Одна из крупнейших однообъектных солнечных станций мира, использует двусторонние панели с трекерами, близ Абу-Даби.' },
  { id:143, name:'Cestas Solar Park', nameRu:'СЭС Сеста', type:'solar',
    lng:-0.685, lat:44.730, capacity:300, country:'France', countryRu:'Франция',
    river:null, status:'active', year:2015, annual:'0.35 TWh', units:null,
    img: null,
    description:'Largest solar farm in France at the time of completion, built on a former pine forest near Bordeaux.',
    descriptionRu:'Крупнейшая солнечная станция Франции на момент завершения, построена на месте бывшего соснового леса близ Бордо.' },
  { id:144, name:'Horns Rev 2 Offshore Wind Farm', nameRu:'Ветропарк Хорнс-Рев 2', type:'wind',
    lng:7.580, lat:55.600, capacity:209, country:'Denmark', countryRu:'Дания',
    river:null, status:'active', year:2009, annual:'0.8 TWh', units:91,
    img: null,
    description:'A North Sea offshore wind farm off the Jutland coast, part of Denmark\'s pioneering offshore wind programme.',
    descriptionRu:'Офшорный ветропарк в Северном море у побережья Ютландии, часть пионерской программы офшорной ветроэнергетики Дании.' },

  // ── HISTORIC / DECOMMISSIONED NUCLEAR ──────────────────────
  { id:200, name:'Chernobyl Nuclear Power Plant', nameRu:'Чернобыльская АЭС', type:'nuclear',
    lng:30.099, lat:51.389, capacity:4000, country:'Ukraine', countryRu:'Украина',
    river:'Pripyat', riverRu:'Припять', status:'decommissioned', year:1977, annual:'0 TWh', units:4,
    img: IMG('Chernobyl_Nuclear_Power_Plant.jpg'),
    description:'Site of the worst nuclear accident in history (1986). Reactor 4 exploded, creating a 30 km exclusion zone that remains in place today.',
    descriptionRu:'Место крупнейшей ядерной катастрофы в истории (1986). Взрыв 4-го реактора создал 30-километровую зону отчуждения, существующую до сих пор.' },
  { id:201, name:'Fukushima Daiichi Nuclear Power Plant', nameRu:'АЭС Фукусима-1', type:'nuclear',
    lng:141.033, lat:37.421, capacity:4696, country:'Japan', countryRu:'Япония',
    river:null, status:'decommissioned', year:1971, annual:'0 TWh', units:6,
    img: IMG('Fukushima_I_by_Digital_Globe.jpg'),
    description:'Crippled by the 2011 Tōhoku earthquake and tsunami, causing a triple meltdown. Decommissioning is expected to take decades.',
    descriptionRu:'Повреждена землетрясением и цунами Тохоку в 2011 г., что привело к тройному расплавлению топлива. Демонтаж займёт десятилетия.' },
  { id:202, name:'Three Mile Island Nuclear Generating Station', nameRu:'АЭС Три-Майл-Айленд', type:'nuclear',
    lng:-76.725, lat:40.153, capacity:880, country:'USA', countryRu:'США',
    river:'Susquehanna', riverRu:'Саскуэханна', status:'decommissioned', year:1974, annual:'0 TWh', units:1,
    img: IMG('Three_Mile_Island_Nuclear_Generating_Station.jpg'),
    description:'Site of the most significant nuclear accident in US commercial power history (1979, partial meltdown). The surviving unit closed in 2019.',
    descriptionRu:'Место крупнейшей в истории коммерческой ядерной энергетики США аварии (1979, частичное расплавление). Уцелевший блок закрыт в 2019 г.' },
  { id:203, name:'Sellafield (Calder Hall)', nameRu:'Селлафилд (Колдер-Холл)', type:'nuclear',
    lng:-3.500, lat:54.420, capacity:200, country:'UK', countryRu:'Великобритания',
    river:null, status:'decommissioned', year:1956, annual:'0 TWh', units:4,
    img: IMG('Sellafield_geograph-3759316-by-Ben-Brooksbank.jpg'),
    description:'Calder Hall was the world\'s first commercial-scale nuclear power station, opened in 1956. The site is now a major nuclear reprocessing facility.',
    descriptionRu:'Колдер-Холл — первая в мире коммерческая атомная электростанция, открыта в 1956 г. Сейчас на площадке расположен крупный завод по переработке ядерного топлива.' },
  { id:204, name:'Kakhovka Dam', nameRu:'Каховская ГЭС', type:'hydro',
    lng:33.378, lat:46.781, capacity:357, country:'Ukraine', countryRu:'Украина',
    river:'Dnieper', riverRu:'Днепр', status:'decommissioned', year:1956, annual:'0 TWh', units:6,
    img: IMG('Kakhovka_Dam_before_destruction.jpg'),
    description:'Destroyed in June 2023 during the Russian invasion, draining the vast Kakhovka Reservoir and causing a major ecological disaster.',
    descriptionRu:'Разрушена в июне 2023 года во время российского вторжения, что привело к осушению огромного Каховского водохранилища и крупной экологической катастрофе.' },

  // ── MORE HYDRO WORLDWIDE ────────────────────────────────────
  { id:210, name:'Glen Canyon Dam', nameRu:'Плотина Глен-Каньон', type:'hydro',
    lng:-111.483, lat:36.937, capacity:1320, country:'USA', countryRu:'США',
    river:'Colorado', riverRu:'Колорадо', status:'active', year:1966, annual:'4 TWh', units:8,
    img: IMG('Glen_Canyon_Dam_from_air.jpg'),
    description:'Forms Lake Powell, the second-largest reservoir in the USA. A focal point of debates over Colorado River water management.',
    descriptionRu:'Создаёт озеро Пауэлл — второе по величине водохранилище США. Центр споров об управлении водными ресурсами реки Колорадо.' },
  { id:211, name:'Oroville Dam', nameRu:'Плотина Оровилл', type:'hydro',
    lng:-121.484, lat:39.539, capacity:819, country:'USA', countryRu:'США',
    river:'Feather', riverRu:'Фезер', status:'active', year:1968, annual:'2.2 TWh', units:6,
    img: IMG('Oroville_Dam.jpg'),
    description:'Tallest dam in the United States (230 m). Its emergency spillway failure in 2017 forced the evacuation of 188,000 people.',
    descriptionRu:'Самая высокая плотина США (230 м). Авария на аварийном водосбросе в 2017 году привела к эвакуации 188 000 человек.' },
  { id:212, name:'La Rance Tidal Power Station', nameRu:'Приливная ПЭС Ранс', type:'hydro',
    lng:-1.971, lat:48.620, capacity:240, country:'France', countryRu:'Франция',
    river:'Rance estuary', riverRu:'Эстуарий Ранс', status:'active', year:1966, annual:'0.5 TWh', units:24,
    img: IMG('Rance_tidal_power_station.jpg'),
    description:'World\'s first tidal power station, harnessing the Rance estuary\'s tidal range — one of the largest in the world.',
    descriptionRu:'Первая в мире приливная электростанция, использует один из крупнейших в мире приливных диапазонов эстуария реки Ранс.' },
  { id:213, name:'Sihwa Lake Tidal Power Station', nameRu:'Приливная ПЭС Сихва', type:'hydro',
    lng:126.611, lat:37.310, capacity:254, country:'South Korea', countryRu:'Южная Корея',
    river:'Sihwa Lake', riverRu:'озеро Сихва', status:'active', year:2011, annual:'0.55 TWh', units:10,
    img: IMG('Sihwa_Lake_Tidal_Power_Plant.jpg'),
    description:'World\'s largest tidal power station by installed capacity, built into an existing seawall on Korea\'s west coast.',
    descriptionRu:'Крупнейшая в мире приливная электростанция по установленной мощности, встроена в существующую дамбу на западном побережье Кореи.' },
  { id:214, name:'Volzhskaya HPP', nameRu:'Волжская ГЭС', type:'hydro',
    lng:44.730, lat:48.780, capacity:2671, country:'Russia', countryRu:'Россия',
    river:'Volga', riverRu:'Волга', status:'active', year:1961, annual:'11.1 TWh', units:22,
    img: IMG('Volga_Hydroelectric_Station.jpg'),
    description:'One of the largest hydroelectric stations in Europe, near Volgograd, regulating flow on the lower Volga River.',
    descriptionRu:'Одна из крупнейших ГЭС Европы, близ Волгограда, регулирует сток на нижней Волге.' },
  { id:215, name:'Boguchany HPP', nameRu:'Богучанская ГЭС', type:'hydro',
    lng:96.693, lat:58.661, capacity:3000, country:'Russia', countryRu:'Россия',
    river:'Angara', riverRu:'Ангара', status:'active', year:2012, annual:'17.6 TWh', units:9,
    img: null,
    description:'The last large Soviet-designed hydroelectric project, completed decades after construction began, on the Angara River.',
    descriptionRu:'Последний крупный гидроэнергетический проект советского проектирования, завершён спустя десятилетия после начала строительства, на реке Ангара.' },

  // ── MORE COAL WORLDWIDE ─────────────────────────────────────
  { id:220, name:'Drax Power Station', nameRu:'ТЭС Дракс', type:'coal',
    lng:-0.998, lat:53.737, capacity:3960, country:'UK', countryRu:'Великобритания',
    river:'Ouse', riverRu:'Уз', status:'active', year:1974, annual:'14 TWh', units:6,
    img: IMG('Drax_power_station_(geograph_4060462).jpg'),
    description:'Largest power station in the UK, originally coal-fired and now substantially converted to burn imported wood pellet biomass.',
    descriptionRu:'Крупнейшая электростанция Великобритании, изначально угольная, теперь в значительной степени переведена на импортные древесные пеллеты.' },
  { id:221, name:'Plant Scherer', nameRu:'ТЭС Шерер', type:'coal',
    lng:-83.820, lat:33.054, capacity:3564, country:'USA', countryRu:'США',
    river:null, status:'active', year:1982, annual:'20 TWh', units:4,
    img: IMG('Plant_Scherer.jpg'),
    description:'The largest coal-fired power plant in the United States by capacity, located in Georgia, and a major historical CO₂ emitter.',
    descriptionRu:'Крупнейшая угольная электростанция США по мощности, расположена в штате Джорджия, крупный исторический эмитент CO₂.' },
  { id:222, name:'Eraring Power Station', nameRu:'ТЭС Эраринг', type:'coal',
    lng:151.467, lat:-33.067, capacity:2880, country:'Australia', countryRu:'Австралия',
    river:null, status:'active', year:1982, annual:'15 TWh', units:4,
    img: IMG('Eraring_Power_Station.jpg'),
    description:'Largest power station in Australia, on the shores of Lake Macquarie in New South Wales, scheduled for eventual closure.',
    descriptionRu:'Крупнейшая электростанция Австралии, на берегу озера Маккуори в Новом Южном Уэльсе, планируется к закрытию.' },
  { id:223, name:'Loy Yang Power Station', nameRu:'ТЭС Лой-Янг', type:'coal',
    lng:146.590, lat:-38.252, capacity:2210, country:'Australia', countryRu:'Австралия',
    river:null, status:'active', year:1984, annual:'13 TWh', units:4,
    img: IMG('Loy_Yang_Power_Station.jpg'),
    description:'Burns brown coal from an adjacent open-cut mine in the Latrobe Valley, one of Australia\'s most carbon-intensive plants.',
    descriptionRu:'Сжигает бурый уголь из соседнего открытого разреза в долине Латроб, одна из самых углеродоёмких станций Австралии.' },

  // ── MORE SOLAR WORLDWIDE (with images) ──────────────────────
  { id:230, name:'Datong Solar Power Top Runner Base ("Panda Plant")', nameRu:'Солнечная станция «Панда» (Датун)', type:'solar',
    lng:113.470, lat:40.180, capacity:248, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2017, annual:'0.4 TWh', units:null,
    img: IMG('Panda_Power_Plant.jpg'),
    description:'A solar farm shaped like a giant panda when viewed from above, designed to inspire children\'s interest in renewable energy.',
    descriptionRu:'Солнечная станция в форме гигантской панды при виде сверху, призвана прививать детям интерес к возобновляемой энергетике.' },
  { id:231, name:'Kamuthi Solar Power Project', nameRu:'СЭС Камутхи', type:'solar',
    lng:78.382, lat:9.348, capacity:648, country:'India', countryRu:'Индия',
    river:null, status:'active', year:2016, annual:'1.5 TWh', units:null,
    img: IMG('Kamuthi_Solar_Power_Project.jpg'),
    description:'One of the largest single-location solar power plants at the time, built in just eight months in Tamil Nadu.',
    descriptionRu:'Одна из крупнейших на момент постройки солнечных станций на одной площадке, построена всего за восемь месяцев в Тамилнаду.' },
  { id:232, name:'Villanueva Solar Park', nameRu:'СЭС Вильянуэва', type:'solar',
    lng:-100.700, lat:25.700, capacity:828, country:'Mexico', countryRu:'Мексика',
    river:null, status:'active', year:2018, annual:'1.7 TWh', units:null,
    img: null,
    description:'Largest solar park in the Americas at the time of completion, located in Coahuila state.',
    descriptionRu:'Крупнейший солнечный парк Северной и Южной Америки на момент завершения, расположен в штате Коауила.' },
  { id:233, name:'Rewa Ultra Mega Solar Park', nameRu:'СЭС Рева', type:'solar',
    lng:81.345, lat:24.535, capacity:750, country:'India', countryRu:'Индия',
    river:null, status:'active', year:2018, annual:'1.5 TWh', units:null,
    img: null,
    description:'One of India\'s flagship solar parks, supplying power to the Delhi Metro and household consumers in Madhya Pradesh.',
    descriptionRu:'Один из флагманских солнечных парков Индии, снабжает энергией метро Дели и потребителей в штате Мадхья-Прадеш.' },

  // ── MORE WIND WORLDWIDE (with images) ───────────────────────
  { id:240, name:'Middelgrunden Offshore Wind Farm', nameRu:'Ветропарк Мидделгрюнден', type:'wind',
    lng:12.650, lat:55.685, capacity:40, country:'Denmark', countryRu:'Дания',
    river:null, status:'active', year:2000, annual:'0.1 TWh', units:20,
    img: IMG('Middelgrunden_Wind_Farm.jpg'),
    description:'Iconic curved offshore wind farm visible from Copenhagen, one of the first large community-owned wind projects.',
    descriptionRu:'Знаменитый изогнутый офшорный ветропарк, виден из Копенгагена, один из первых крупных проектов с общинным владением.' },
  { id:241, name:'Block Island Wind Farm', nameRu:'Ветропарк Блок-Айленд', type:'wind',
    lng:-71.520, lat:41.130, capacity:30, country:'USA', countryRu:'США',
    river:null, status:'active', year:2016, annual:'0.125 TWh', units:5,
    img: IMG('Block_Island_Wind_Farm_(29393789854).jpg'),
    description:'The first offshore wind farm in the United States, located off the coast of Rhode Island.',
    descriptionRu:'Первый офшорный ветропарк в США, расположен у побережья штата Род-Айленд.' },
  { id:242, name:'Burbo Bank Offshore Wind Farm', nameRu:'Ветропарк Бурбо-Бэнк', type:'wind',
    lng:-3.200, lat:53.480, capacity:90, country:'UK', countryRu:'Великобритания',
    river:null, status:'active', year:2007, annual:'0.3 TWh', units:25,
    img: IMG('Burbo_Bank_Offshore_Wind_Farm.jpg'),
    description:'One of the UK\'s early offshore wind farms, visible from Liverpool and Crosby beaches at the mouth of the River Mersey.',
    descriptionRu:'Один из ранних офшорных ветропарков Великобритании, виден с пляжей Ливерпуля и Кросби в устье реки Мерси.' },
  { id:243, name:'Thanet Offshore Wind Farm', nameRu:'Ветропарк Тейнет', type:'wind',
    lng:1.630, lat:51.430, capacity:300, country:'UK', countryRu:'Великобритания',
    river:null, status:'active', year:2010, annual:'1 TWh', units:100,
    img: null,
    description:'Was the world\'s largest offshore wind farm upon completion in 2010, off the Kent coast.',
    descriptionRu:'На момент завершения в 2010 году — крупнейший офшорный ветропарк мира, у побережья графства Кент.' },

  // ── MORE GAS / OIL WORLDWIDE ─────────────────────────────────
  { id:250, name:'Korea Incheon Combined Cycle Power Plant', nameRu:'ТЭС Инчхон (комб. цикл)', type:'gas',
    lng:126.638, lat:37.450, capacity:1800, country:'South Korea', countryRu:'Южная Корея',
    river:null, status:'active', year:1995, annual:'9 TWh', units:8,
    img: null,
    description:'One of South Korea\'s major LNG combined-cycle plants, supplying the densely populated Seoul metropolitan area.',
    descriptionRu:'Одна из крупных газовых электростанций Южной Кореи комбинированного цикла на СПГ, снабжает плотно населённый Сеульский регион.' },
  { id:251, name:'Ravenna Gas Power Plant', nameRu:'ТЭС Равенна', type:'gas',
    lng:12.200, lat:44.420, capacity:980, country:'Italy', countryRu:'Италия',
    river:null, status:'active', year:2008, annual:'4.5 TWh', units:2,
    img: null,
    description:'A modern combined-cycle gas plant on Italy\'s Adriatic coast, part of the country\'s gas-heavy generation mix.',
    descriptionRu:'Современная газовая станция комбинированного цикла на адриатическом побережье Италии, часть газовой генерации страны.' },

  // ── SOUTHERN EUROPE / BALKANS ────────────────────────────────
  { id:260, name:'Alqueva Dam', nameRu:'Плотина Алкева', type:'hydro',
    lng:-7.500, lat:38.200, capacity:520, country:'Portugal', countryRu:'Португалия',
    river:'Guadiana', riverRu:'Гвадиана', status:'active', year:2004, annual:'1 TWh', units:4,
    img: IMG('Alqueva_Dam.jpg'),
    description:'Forms the largest artificial lake in Western Europe by area, also supporting one of the world\'s largest floating solar plants.',
    descriptionRu:'Создаёт крупнейшее по площади искусственное озеро Западной Европы, также поддерживает одну из крупнейших плавучих СЭС мира.' },
  { id:261, name:'Kremasta Dam', nameRu:'Плотина Кремаста', type:'hydro',
    lng:21.450, lat:38.880, capacity:437, country:'Greece', countryRu:'Греция',
    river:'Acheloos', riverRu:'Ахелоос', status:'active', year:1965, annual:'0.6 TWh', units:4,
    img: null,
    description:'Largest hydroelectric dam in Greece, on the Acheloos River, forming the country\'s largest artificial lake.',
    descriptionRu:'Крупнейшая ГЭС Греции, на реке Ахелоос, образует крупнейшее искусственное озеро страны.' },
  { id:262, name:'Iron Gate I Hydroelectric Plant', nameRu:'ГЭС Джердап-1 (Железные Ворота)', type:'hydro',
    lng:22.530, lat:44.670, capacity:2160, country:'Romania/Serbia', countryRu:'Румыния/Сербия',
    river:'Danube', riverRu:'Дунай', status:'active', year:1972, annual:'10.5 TWh', units:12,
    img: IMG('Iron_Gate_I_Hydroelectric_Power_Station.jpg'),
    description:'One of the largest dams on the Danube River, jointly operated by Romania and Serbia.',
    descriptionRu:'Одна из крупнейших плотин на реке Дунай, совместно эксплуатируется Румынией и Сербией.' },

  // ── SOUTH AMERICA & MEXICO ───────────────────────────────────
  { id:270, name:'Salto Grande Dam', nameRu:'ГЭС Сальто-Гранде', type:'hydro',
    lng:-57.930, lat:-31.280, capacity:1890, country:'Argentina/Uruguay', countryRu:'Аргентина/Уругвай',
    river:'Uruguay', riverRu:'Уругвай', status:'active', year:1979, annual:'8 TWh', units:14,
    img: IMG('Salto_Grande_Dam.jpg'),
    description:'A binational dam on the Uruguay River shared by Argentina and Uruguay, also carrying a major road crossing.',
    descriptionRu:'Двунациональная плотина на реке Уругвай, общая для Аргентины и Уругвая, также несёт крупную автодорожную переправу.' },
  { id:271, name:'Chicoasén Dam (Manuel Moreno Torres)', nameRu:'ГЭС Чикоасен', type:'hydro',
    lng:-93.100, lat:16.950, capacity:2400, country:'Mexico', countryRu:'Мексика',
    river:'Grijalva', riverRu:'Грихальва', status:'active', year:1980, annual:'5 TWh', units:8,
    img: null,
    description:'One of the tallest dams in the world, on the Grijalva River in Chiapas, Mexico\'s largest hydroelectric plant.',
    descriptionRu:'Одна из самых высоких плотин мира, на реке Грихальва в штате Чьяпас, крупнейшая ГЭС Мексики.' },

  // ── MORE NUCLEAR (operating) ──────────────────────────────────
  { id:280, name:'Hanul Nuclear Power Plant', nameRu:'АЭС Ханул', type:'nuclear',
    lng:129.388, lat:37.094, capacity:6189, country:'South Korea', countryRu:'Южная Корея',
    river:null, status:'active', year:1988, annual:'48 TWh', units:6,
    img: null,
    description:'One of the largest nuclear power complexes in South Korea, on the east coast of the peninsula.',
    descriptionRu:'Один из крупнейших атомных комплексов Южной Кореи, на восточном побережье полуострова.' },
  { id:281, name:'Hanbit Nuclear Power Plant', nameRu:'АЭС Ханбит', type:'nuclear',
    lng:126.423, lat:35.412, capacity:5875, country:'South Korea', countryRu:'Южная Корея',
    river:null, status:'active', year:1986, annual:'45 TWh', units:6,
    img: null,
    description:'A major South Korean nuclear site on the southwest coast, formerly known as Yeonggwang.',
    descriptionRu:'Крупная атомная площадка Южной Кореи на юго-западном побережье, ранее известная как Йонгван.' },
  { id:282, name:'Fuqing Nuclear Power Plant', nameRu:'АЭС Фуцин', type:'nuclear',
    lng:119.450, lat:25.300, capacity:6494, country:'China', countryRu:'Китай',
    river:null, status:'active', year:2014, annual:'48 TWh', units:6,
    img: null,
    description:'Home to the first Hualong One (HPR-1000) reactor, China\'s domestically designed third-generation nuclear technology.',
    descriptionRu:'Здесь работает первый реактор «Хуалун-1» (HPR-1000) — китайская технология третьего поколения собственной разработки.' },

  // ── MORE OCEANIA / ANTARCTICA-ADJACENT ──────────────────────
  { id:290, name:'Hydro Tasmania Gordon Dam', nameRu:'Плотина Гордон (Тасмания)', type:'hydro',
    lng:146.110, lat:-42.770, capacity:432, country:'Australia', countryRu:'Австралия',
    river:'Gordon', riverRu:'Гордон', status:'active', year:1978, annual:'1 TWh', units:3,
    img: IMG('Gordon_Dam_Tasmania.jpg'),
    description:'A spectacular double-curvature arch dam in Tasmania\'s wilderness, central to the island\'s nearly all-renewable grid.',
    descriptionRu:'Впечатляющая арочная плотина двойной кривизны в дикой природе Тасмании, основа почти полностью возобновляемой энергосистемы острова.' },
  { id:291, name:'Macarthur Wind Farm', nameRu:'Ветропарк Макартур', type:'wind',
    lng:142.350, lat:-38.020, capacity:420, country:'Australia', countryRu:'Австралия',
    river:null, status:'active', year:2012, annual:'1.4 TWh', units:140,
    img: null,
    description:'One of the largest wind farms in the Southern Hemisphere at the time, in the Victorian countryside.',
    descriptionRu:'Один из крупнейших ветропарков Южного полушария на момент постройки, в сельской местности штата Виктория.' },
]
